### ISSUE TITLE
The provided distributed example is too slow

### ISSUE THREAD

**Issue by wizard1203** [alibaba/FederatedScope#344]
Thanks for your awesome works of FederatedScope.

I follow the tutorial to conduct distributed exp. 

```# For server
python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_femnist_server.yaml &
sleep 2

# For clients
python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_femnist_client_1.yaml &
sleep 2
python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_femnist_client_2.yaml &
sleep 2
python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_femnist_client_3.yaml &
```

Each client takes around 4\~5 minutes to finish its local training. And it seems that the sampled clients conduct training sequentially rather than parallelly. Because clients print the logger info one by one after 4\~5 minutes.
I assign each client with an individual GPU. The GPU util is around 0%. So the bottleneck seems not GPU computation. Is there any possible reason of this?

![image](https://user-images.githubusercontent.com/22996426/186077206-adde96f0-cc0b-4d00-9fa7-9d825d2aff2f.png)
![image](https://user-images.githubusercontent.com/22996426/186077282-3c93a7da-329f-45f3-ba01-103c55ab417e.png)

**Comment by xieyxclack** [comment]
Thanks for your interest! :) 

If your run FederatedScope with distributed mode, each client is instantiated with one procedure (i.e., python main.py -cfg xxx), therefore they would be run parallelly rather than sequentially. And it seems that the communication process takes most of the time, i.e., sending and receiving the model parameters, which is implemented via gRPC by default in distributed mode. So that the GPU util is around 0% as you mentioned.

The communication speed is related to the model size and available bandwidth, maybe you can choose a smaller mode first, Thank you!

**Comment by wizard1203** [comment]
Thanks for your reply. Yeah, it maybe the communication problem... Let try more cases.
