### ISSUE TITLE
Can I get the client ID information inside ctx  class?

### ISSUE THREAD

**Issue by krishnakanthnakka** [alibaba/FederatedScope#711]
Dear @rayrayraykk ,

I went through the documentation of `ctx` class in https://github.com/alibaba/FederatedScope/blob/master/federatedscope/core/trainers/README.md 

I'm wondering if there's a variable to retrieve the worker ID inside the ctx enviroment?  For instance `ctx` has members like `cfg`, `ys_true`, `cur_split`, and more... but sometimes, I would need the information about `clientID` (ie `worker ID`, which ranges from `1` to `number of clients`). Is this information available? 

If it is not available, can you please provide some guidance on this?

**Comment by rayrayraykk** [comment]
Thanks for your interest in FS. Sorry that the `worker ID` is not available in Trainer now because the Trainer is Instantiated before the client gets the ID from the server. But I would like to help you achieve this function.

You can add a function for Trainer after the client gets the worker ID. Since the standalone and distributed mode does not share the same at the beginning stage, I recommend you modify the codes as follows:

Before:
https://github.com/alibaba/FederatedScope/blob/480b67de851df2fa02b7cc2189f1803d947998d7/federatedscope/core/workers/client.py#L247 
After:
```python
    def callback_funcs_for_model_para(self, message: Message):
        # add new line here
        self.trainer.update_idx(self.ID)
        ...
```

Before: https://github.com/alibaba/FederatedScope/blob/480b67de851df2fa02b7cc2189f1803d947998d7/federatedscope/core/trainers/base_trainer.py#L35

After:
```python
    ...
    # add a new function here. For torchtrainer, you can change to `self.ctx.idx = idx` for consistency
    def update_idx(self, idx):
        self.idx = idx
    ...
```

I hope this solves your problem.
Ps. remember to re-install the package after the modification.

**Comment by krishnakanthnakka** [comment]
Wonderful. Thank you, I can retrieve the`ID` with the above changes.
