### ISSUE TITLE
run error about llm

### ISSUE THREAD

**Issue by JobsWangHaoQuan** [alibaba/FederatedScope#712]
Hello, I have some questions when I run the llm
use the 'python federatedscope/main.py --cfg federatedscope/llm/baseline/testcase.yaml'

The domestic users are unable to connect to Hugging Face, hence consistently encountering errors：

```
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like gpt2 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
```
What should I do to solve this problem?

Hope you have time to help me with this problem, thank you!

**Comment by rayrayraykk** [comment]
Hello, thanks for your interest in FS-LLM! 
This error looks like it is caused by a network error that blocks you from downloading the model from hugging face. You can download the model as well as the tokenizer file using a mirror site or publicly available methods (e.g. collab). Then run the script by specifying `llm.cache.model` as `/SOME_PATH/gpt-2` (where your downloaded files are saved).
